apiVersion: v1
name: soroban-rpc
version: 0.1.1
appVersion: "0.9.3"
description: Stellar Soroban RPC Helm Chart. This chart will deploy Stellar Soroban API server
maintainers:
  - name: Stellar Development Foundation
sources:
  - https://github.com/stellar/soroban-tools
  - https://github.com/stellar/helm-charts
