apiVersion: v1
name: horizon
version: 0.0.7
appVersion: "2.26.1"
description: Stellar Horizon Helm Chart. This chart will deploy Stellar Horizon API server
maintainers: 
  - name: Stellar Development Foundation
sources:
  - https://github.com/stellar/go
  - https://github.com/stellar/helm-charts
