---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.fullname" . | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ include "common.fullname" . | quote }}
    chart: {{ include "common.chart" . | quote }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: 1 # Galexie can not currently support multiple pods pushing data to the same place
  selector:
    matchLabels:
      app: {{ include "common.fullname" . | quote }}
  strategy:
    type: Recreate # Delete old pod to release PVC for new pod
  template:
    metadata:
      labels:
        app: {{ include "common.fullname" . | quote }}
    spec:
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ .Values.serviceAccount.name | default (include "common.fullname" .) | quote }}
      {{- else }}
      serviceAccountName: {{ .Values.serviceAccount.name | default "default" | quote }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name | quote }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          command:
            - "galexie"
            - "append"
            - "--config-file=/galexie-config/config.toml"
          {{- range .Values.additionalFlags }}
            - {{ . | quote }}
          {{- end }}
          ports:
            - containerPort: {{ .Values.adminPort }}
          {{- with .Values.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: galexie-config-volume
              mountPath: /galexie-config
            - name: captive-core
              mountPath: /var/lib/stellar
      volumes:
        - name: galexie-config-volume
          configMap:
            name: {{ include "common.fullname" . | quote }}
        - name: captive-core
          persistentVolumeClaim:
            claimName: {{ print (include "common.fullname" .) "-captive-core" | quote }}
