# Admin port where metrics are served
adminPort: 6061

# Stellar core configuration
stellarCore:
  # Which stellar network to use. The preset options are "pubnet" or "testnet".
  # For a custom network configuration leave empty and set history_archive_urls,
  # network_passphrase, and config.
  network: "pubnet"
  # List of history archives used in the network
  history_archive_urls: []
  # Passphrase for the network
  network_passphrase: ""
  # Overwrite the core default config with a full stellar core configuration
  # https://developers.stellar.org/docs/validators/admin-guide/configuring
  # Use a multiline string
  config: ""

# Datastore configuration for files created by Galexie
datastore:
  # The options are "GCS" or "S3"
  type: "GCS"
  params:
    # If using s3, region must be specified
    region: ""
    # The endpoint URL for the S3-compatible storage. Should be left empty for S3 or GCS
    endpoint_url: ""
    # The full path including the bucket name of where to create data
    path: ""
  schema:
    # Number of ledgers per file
    ledgersPerFile: 1
    # Number of files per partition created in the destination folder
    filesPerPartition: 64000

# Image used by the Galexie deployment
image:
  repository: stellar/stellar-galexie
  tag: 24.0.0
  pullPolicy: IfNotPresent

# Galexie command to run. By default run append which exports any missing
# ledger data after start flag and before end flag
galexieCommand: "append"

# Additional flags to append to the galexie command
# By default this includes start - The earliest ledger to create data for in the datastore.
# For quicker catchup, choose a ledger closer to the most recent ledger in the network
additionalFlags:
  - "--start=59000000"

# Annotations on the Galexie deployment
annotations: {}

# Environment variables for the Galexie deployment
env: []
# EnvFrom for the Galexie deployment
envFrom: []

# Resources for the Galexie deployment
resources:
  limits:
    cpu: 3
    memory: 16Gi
  requests:
    cpu: 1.5
    memory: 8Gi

# Service account used by the Galexie deployment
serviceAccount:
  create: true
  name: ""
  annotations: []

# Persistent volume claim for stellar core data used by Galexie
persistentVolumeClaim:
  storageClassName: default
  # 100Gi is recommended for "pubnet". 10Gi is recommended for "testnet"
  storage: 100Gi
  volumeName: ""
  annotations: []
